# Generated by Django 6.1.2 on 2026-10-07 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('orders', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "delivery";',
    reverse_sql='DROP SCHEMA IF EXISTS "delivery" CASCADE;',
    ),
        migrations.CreateModel(
            name='DeliveryGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_gateways', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Delivery Gateway',
                'verbose_name_plural': 'Delivery Gateways',
                'db_table': '"delivery"."delivery_gateways"',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=30)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_gateway', models.ForeignKey(db_column='delivery_gateway_id', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='delivery.deliverygateway')),
                ('fulfillment', models.ForeignKey(db_column='fulfillment_id', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='fulfillment.fulfillment')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': '"delivery"."shipments"',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to='delivery.shipment')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'db_table': '"delivery"."tracking_events"',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='orders.orderitem')),
                ('shipment', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='delivery.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Item',
                'verbose_name_plural': 'Shipment Items',
                'db_table': '"delivery"."shipment_items"',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_shipment_item_quantity_positive')],
            },
        ),
    ]
