# Generated by Django 6.1.2 on 2026-10-07 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "payments";',
    reverse_sql='DROP SCHEMA IF EXISTS "payments" CASCADE;',
    ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, db_column='order_id', null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=30)),
                ('provider', models.CharField(max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.ForeignKey(blank=True, db_column='checkout_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.checkout')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': '"payments"."payments"',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=30)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': '"payments"."payment_transactions"',
            },
        ),
    ]
