# Generated by Django 6.1.2 on 2026-10-08 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS "themes";',
            reverse_sql='DROP SCHEMA IF EXISTS "themes";',
        ),
        migrations.CreateModel(
            name='ThemeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='theme_files', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Theme file',
                'verbose_name_plural': 'Theme files',
                'db_table': '"themes"."theme_files"',
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('store', 'path'), name='unique_theme_file_path_per_store')],
            },
        ),
    ]
