# Generated by Django 6.1.2 on 2026-10-08 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "themes";',
    reverse_sql='DROP SCHEMA IF EXISTS "themes" CASCADE;',
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('theme_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'db_table': '"themes"."themes"',
            },
        ),
        migrations.CreateModel(
            name='ThemeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('is_editable', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.PROTECT, related_name='files', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Theme File',
                'verbose_name_plural': 'Theme Files',
                'db_table': '"themes"."theme_files"',
            },
        ),
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installed_version', models.CharField(max_length=20)),
                ('custom_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='theme_assignments', to='tenancy.store')),
                ('theme', models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.PROTECT, related_name='store_assignments', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Store Theme',
                'verbose_name_plural': 'Store Themes',
                'db_table': '"themes"."store_themes"',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('store',), name='uq_store_theme_active')],
            },
        ),
    ]
