# Generated by Django 6.1.2 on 2026-10-07 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.RunSQL(
        sql='CREATE SCHEMA IF NOT EXISTS "tenancy";',
        reverse_sql='DROP SCHEMA IF EXISTS "tenancy";',
    ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('store_slug', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': '"tenancy"."stores"',
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.store')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Membership',
                'verbose_name_plural': 'Store Memberships',
                'db_table': '"tenancy"."store_memberships"',
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='uq_store_membership_user_store')],
            },
        ),
    ]
