# Generated by Django 6.1.2 on 2026-10-07 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
        sql='CREATE SCHEMA IF NOT EXISTS "identity";',
        reverse_sql='DROP SCHEMA IF EXISTS "identity";',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('password', models.TextField(db_column='password_hash')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': '"identity"."users"',
            },
        ),
    ]
