# Generated by Django 6.1.2 on 2026-10-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_collection_productimage_productvariant_saleschannel_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
        sql='CREATE SCHEMA IF NOT EXISTS "inventory";',
        reverse_sql='DROP SCHEMA IF EXISTS "inventory" CASCADE;',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Inventory Location',
                'verbose_name_plural': 'Inventory Locations',
                'db_table': '"inventory"."locations"',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(db_column='destination_location_id', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.location')),
                ('source_location', models.ForeignKey(db_column='source_location_id', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.location')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Inventory Transfer',
                'verbose_name_plural': 'Inventory Transfers',
                'db_table': '"inventory"."transfers"',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unavailable', models.IntegerField()),
                ('committed', models.IntegerField()),
                ('available', models.IntegerField()),
                ('on_hand', models.IntegerField()),
                ('incoming', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.productvariant')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': '"inventory"."inventory_items"',
                'constraints': [models.UniqueConstraint(fields=('variant', 'location'), name='uq_inventory_item_variant_location')],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('transfer', models.ForeignKey(db_column='transfer_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.transfer')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Transfer Item',
                'verbose_name_plural': 'Transfer Items',
                'db_table': '"inventory"."transfer_items"',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_transfer_item_quantity_positive')],
            },
        ),
    ]
