# Generated by Django 6.1.2 on 2026-10-07 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_collection_productimage_productvariant_saleschannel_and_more'),
        ('orders', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "discounts";',
    reverse_sql='DROP SCHEMA IF EXISTS "discounts" CASCADE;',
    ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('per_customer_limit', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': '"discounts"."discounts"',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount', models.ForeignKey(db_column='discount_id', on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='discounts.discount')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'db_table': '"discounts"."discount_codes"',
            },
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount', models.ForeignKey(db_column='discount_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='discounts.discount')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='discount_products', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Discount Product',
                'verbose_name_plural': 'Discount Products',
                'db_table': '"discounts"."discount_products"',
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount', models.ForeignKey(db_column='discount_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_discounts', to='discounts.discount')),
                ('discount_code', models.ForeignKey(blank=True, db_column='discount_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_discounts', to='discounts.discountcode')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Discount',
                'verbose_name_plural': 'Order Discounts',
                'db_table': '"discounts"."order_discounts"',
            },
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(fields=('discount', 'code'), name='uq_discount_code'),
        ),
        migrations.AddConstraint(
            model_name='discountproduct',
            constraint=models.UniqueConstraint(fields=('discount', 'product'), name='uq_discount_product'),
        ),
    ]
