# Generated by Django 6.1.2 on 2026-10-07 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "gift_cards";',
    reverse_sql='DROP SCHEMA IF EXISTS "gift_cards" CASCADE;',
    ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='customers.customer')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'db_table': '"gift_cards"."gift_cards"',
            },
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(blank=True, db_column='checkout_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to='commerce.checkout')),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to=settings.AUTH_USER_MODEL)),
                ('gift_card', models.ForeignKey(db_column='gift_card_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gift_cards.giftcard')),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Gift Card Transaction',
                'verbose_name_plural': 'Gift Card Transactions',
                'db_table': '"gift_cards"."gift_card_transactions"',
            },
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uq_gift_card_store_code'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='ck_gift_card_current_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__lte', models.F('initial_balance'))), name='ck_gift_card_balance_not_above_initial'),
        ),
    ]
