"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# .env has used both names, so accept either.
SECRET_KEY = (
    os.getenv('DJANGO_SECRET_KEY')
    or os.getenv('SECRET_KEY')
    or 'django-insecure-secret-key'
)


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
# Off unless .env says DJANGO_DEBUG=True, so a missing .env never exposes debug pages.
DEBUG = env_bool('DJANGO_DEBUG', default=False)

# Login tokens (JWT) are signed with SECRET_KEY: with the built-in fallback
# anyone could forge them, so it is only allowed while developing.
if SECRET_KEY == 'django-insecure-secret-key' and not DEBUG:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY in .env before running with DEBUG off.')

# Domains this backend may be served on, e.g. "api.example.com"
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')

# Frontend origins allowed to send forms/cookies to this backend (must include https://)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.core',
    'apps.identity',
    'apps.tenancy',
    'apps.customers',
    'apps.catalog',
    'apps.inventory',
    'apps.purchasing',
    'apps.commerce',
    'apps.payments',
    'apps.orders',
    'apps.delivery',
    'apps.wishlist',
    'apps.discounts',
    'apps.gift_cards',
    'apps.fulfillment',
    'apps.themes',
    
]

AUTH_USER_MODEL = "identity.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files (product photos). Served by Django only while DEBUG is on;
# in production the web server or a storage bucket serves MEDIA_URL.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Sender of account emails (password reset, email verification)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@localhost')

# Links in those emails open the frontend (see apps/identity/email_links.py)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# How long the links work
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', 60 * 60))  # 1 hour
EMAIL_VERIFICATION_TIMEOUT = int(os.getenv('EMAIL_VERIFICATION_TIMEOUT', 60 * 60 * 24 * 3))  # 3 days

# No email provider yet: emails are printed in the runserver console.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Allow the Next.js frontend to call the API from the browser
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173',
)
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'x-store-id',
]


# API: every endpoint needs a signed-in user unless the view says otherwise.
# Store-owned endpoints also need the X-Store-Id header (see apps/core/permissions.py).
REST_FRAMEWORK = {
    # A JWT ("Authorization: Bearer ...") or the Django session cookie set at
    # sign-in; session requests must also send the CSRF token.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.core.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Slows down password guessing on sign-in / sign-up (see identity views)
    'DEFAULT_THROTTLE_RATES': {
        'auth': '10/min',
        # Password reset / verification emails: stops mailbox flooding
        'email': '5/hour',
    },
}


# JWT login tokens (djangorestframework-simplejwt)
# - access:  sent with every API request; short-lived
# - refresh: only used to get a new access token; long-lived
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'UPDATE_LAST_LOGIN': False,
}
# "Remember me" keeps the refresh token for longer (see apps/core/tokens.py)
JWT_REMEMBER_ME_REFRESH_LIFETIME = timedelta(days=30)


# Django sessions (django_session table): the cookie session for /admin/ and
# browser sign-in, and the server-side record behind each JWT sign-in, which
# makes sign-out and single-use refresh tokens work (see apps/core/tokens.py).
# Without "remember me" the cookie ends when the browser closes.
# Remove expired rows now and then with: python manage.py clearsessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = int(JWT_REMEMBER_ME_REFRESH_LIFETIME.total_seconds())
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Password hashing: Argon2 for new passwords. Older PBKDF2 hashes still work
# and are upgraded to Argon2 automatically the next time that user signs in.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Production security (only when DEBUG is off, so local http:// still works)
# https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
# Secure session/CSRF cookies are set with the session settings above.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

if not DEBUG:
    # Send every http:// request to https://
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
    # Behind a proxy/load balancer that terminates HTTPS (Render, Railway, Nginx...)
    # set DJANGO_BEHIND_PROXY=True, otherwise the redirect above loops forever.
    if env_bool('DJANGO_BEHIND_PROXY', default=False):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Tell browsers to only ever use HTTPS for this site
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_HSTS_INCLUDE_SUBDOMAINS', default=False)
    SECURE_HSTS_PRELOAD = False
