# Generated by Django 6.1.2 on 2026-10-07 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_collection_productimage_productvariant_saleschannel_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
        sql='CREATE SCHEMA IF NOT EXISTS "purchasing";',
        reverse_sql='DROP SCHEMA IF EXISTS "purchasing" CASCADE;',
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': '"purchasing"."purchase_orders"',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('purchase_order', models.ForeignKey(db_column='purchase_order_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchasing.purchaseorder')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': '"purchasing"."purchase_order_items"',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_purchase_order_item_quantity_positive')],
            },
        ),
    ]
