# Generated by Django 6.1.2 on 2026-10-07 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "fulfillment";',
    reverse_sql='DROP SCHEMA IF EXISTS "fulfillment" CASCADE;',
    ),  
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Fulfillment',
                'verbose_name_plural': 'Fulfillments',
                'db_table': '"fulfillment"."fulfillments"',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfillment', models.ForeignKey(db_column='fulfillment_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fulfillment.fulfillment')),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Fulfillment Item',
                'verbose_name_plural': 'Fulfillment Items',
                'db_table': '"fulfillment"."fulfillment_items"',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_fulfillment_item_quantity_positive')],
            },
        ),
    ]
