# Generated by Django 6.1.2 on 2026-10-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_productimage_productvariant_saleschannel_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_item',
            field=models.ForeignKey(blank=True, db_column='order_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_reviews', to='orders.orderitem'),
        ),
    ]
