# Generated by Django 6.1.2 on 2026-10-07 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_collection_productimage_productvariant_saleschannel_and_more'),
        ('customers', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "orders";',
    reverse_sql='DROP SCHEMA IF EXISTS "orders" CASCADE;',
    ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=30)),
                ('fulfillment_status', models.CharField(max_length=30)),
                ('delivery_status', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('sales_channel', models.ForeignKey(blank=True, db_column='sales_channel_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.saleschannel')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': '"orders"."orders"',
            },
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_number', models.CharField(max_length=50)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='draft_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='draft_orders', to='customers.customer')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='draft_orders', to='tenancy.store')),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_draft', to='orders.order')),
            ],
            options={
                'verbose_name': 'Draft Order',
                'verbose_name_plural': 'Draft Orders',
                'db_table': '"orders"."draft_orders"',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': '"orders"."order_items"',
            },
        ),
        migrations.CreateModel(
            name='DraftOrderDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_order', models.ForeignKey(db_column='draft_order_id', on_delete=django.db.models.deletion.PROTECT, related_name='details', to='orders.draftorder')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_order_details', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_order_details', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Draft Order Detail',
                'verbose_name_plural': 'Draft Order Details',
                'db_table': '"orders"."draft_order_details"',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_draft_order_detail_quantity_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.UniqueConstraint(fields=('order',), name='uq_draft_order_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_order_item_quantity_positive'),
        ),
    ]
