# Generated by Django 6.1.2 on 2026-10-07 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_collection_productimage_productvariant_saleschannel_and_more'),
        ('customers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
       migrations.RunSQL(
    sql='CREATE SCHEMA IF NOT EXISTS "wishlist";',
    reverse_sql='DROP SCHEMA IF EXISTS "wishlist" CASCADE;',
    ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='wishlists', to='customers.customer')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='wishlists', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
                'db_table': '"wishlist"."wishlists"',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_items', to='catalog.productvariant')),
                ('wishlist', models.ForeignKey(db_column='wishlist_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wishlist.wishlist')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'db_table': '"wishlist"."wishlist_items"',
            },
        ),
    ]
